version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/web
      - /home/aioramu/Документы/KSP/sss/Animal_Shop.db:/container/path/dbfile

    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
